apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vm-nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf

  - image: gjwnghks99/board:1.0.0
    name: board-api-container
    ports:
    - containerPort: 8080

  volumes:
  - name: vm-nginx-config
    configMap:
      name: nginx-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    worker_processes  1;
    error_log         /var/log/nginx/error.log warn;
    pid               /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include         /etc/nginx/mime.types;
      default_type  application/octet-stream;

      upstream board-api {
        server localhost:8080;
      }

      server {
        listen 80;
        location / {
            proxy_pass http://board-api;
        }
      }

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      # tcp_nopush     on;
      keepalive_timeout  65;
      # gzip  on;
      # include /etc/nginx/conf.d/*.conf;
    }

