services:
  nginx:
    image: nginx
    container_name: web
    volumes:
      - ../week0/daejun/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  board:
    image: k8s-study/board:1.0
    container_name: board