apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  labels:
    app: board
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: gjwnghks99/board:1.0.0
          ports:
            - containerPort: 8080
