apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: board
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
