apiVersion: v1
kind: Pod
metadata:
  name: juwonlee-nginx-pod
  namespace: juwonlee
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
