apiVersion: v1
kind: Pod
metadata:
  name: annotation-pod
  annotations:
    imageRepository: "https://hub.docker.com/r/gjwnghks99/hello/tags"
    githubName: "daejunChoi"
    githubEmail: "joon5380@gmail.com"
spec:
  containers:
    - name: hello-container
      image: gjwnghks99/hello:1.0.0