apiVersion: batch/v1
kind: CronJob
metadata:
  name: board-cronjob
spec:
  schedule: "*/3 * * * *"  # 매 3분마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: board
              image: gjwnghks99/board:1.0.0
          restartPolicy: OnFailure
