apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-board
spec:
  containers:
  - name: board-container
    image: gjwnghks99/board:1.0.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
