services:
  ## nginx
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 9080:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  ## board
  board:
    image: k8s-study/board:1.1
    container_name: board
