apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-canary-deployment
  labels:
    app: board-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
      version: 1.0.4
  template:
    metadata:
      labels:
        app: board
        version: 1.0.4
    spec:
      containers:
        - name: board-container
          image: gjwnghks99/board:1.0.4
          ports:
          - containerPort: 8080