apiVersion: v1
kind: Secret
metadata:
  name: board-secret
stringData:
  spring.application.name: juwonlee-application-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: board-secert-pod
spec:
  containers:
    - name: board-container
      image: gjwnghks99/board:1.0.4
      envFrom:
        - secretRef:
            name: board-secret