apiVersion: v1
kind: Pod
metadata:
  name: yiseoul-nginx-pod
  namespace: yiseoul-namespace
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
