apiVersion: v1
kind: PersistentVolume
metadata:
  name: siyoung-pv-01
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: siyoung-sc
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.8
    path: /tmp