#services:
#  board:
#    image: k8s-study/board:1.0
#    container_name: board
#    ports:
#      - 80:8080

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ../week0/siyoung/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - board
  board:
    image: k8s-study/board:1.0
    container_name: board
    expose:
      - "8080"