apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: juwonlee
spec:
  type: LoadBalancer
  selector:
    app: board
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
