apiVersion: v1
kind: Pod
metadata:
  name: board-liveness-pod
  namespace: juwonlee
  labels:
    app: board-liveness
spec:
  containers:
  - image: gjwnghks99/board:1.0.0
    name: board-container
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /hello
        port: 8080
