apiVersion: v1
kind: Pod

metadata:
  name: board-configmap-pod 

spec:
  containers:
    - name: board-container
      image: gjwnghks99/board:1.0.4
      envFrom:
        - configMapRef:
            name: board-comfigmap
