apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-canary-deployment
  labels:
    app: board-canary-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board
      version: 1.0.3
  template:
    metadata:
      labels:
        app: board
        version: 1.0.3 
    spec:
      containers:
      - name: board-container
        image: gjwnghks99/board:1.0.3
        ports:
        - containerPort: 8080  
