apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.100.100.100
  selector:
    app: board
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080