apiVersion: v1
kind: Pod
metadata:
  name: sangjin-resource-board
spec:
  containers:
   - image: gjwnghks99/board:1.0.0
     name: sangjin-resource-board
     ports:
     - containerPort: 8080
     resources:
       requests:
         cpu: 200m
         memory: 250Mi
       limits:
         cpu: 1
         memory: 500Mi