apiVersion: v1
kind: Pod
metadata:
  name: resource-board-pod
spec:
  containers:
    - name: board
      image: gjwnghks99/board:1.0.0
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 1
          memory: 500Mi