apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: board-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      name: board
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: gjwnghks99/board:1.0.3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: nginx
              topologyKey: kubernetes.io/hostname
