apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-board
spec:
  schedule: "3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: board
              image: gjwnghks99/board:1.0.0
      restartPolicy: Never
